//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""97a0b454-1e5c-4e1e-816c-c27acb6db03c"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""06b2aa77-bf70-474f-bdbe-2e41b6e240c8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseX"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d7cea711-d8f4-415b-a7aa-e4c4c6460939"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""PassThrough"",
                    ""id"": ""89b6e41c-cd0b-40af-b34c-c6a924ae7a11"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Objectives"",
                    ""type"": ""Button"",
                    ""id"": ""6a0101db-dfcd-45ca-bcaa-9aca617235d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickUp"",
                    ""type"": ""Button"",
                    ""id"": ""3d53b0a2-248c-41dc-b01b-943f0f6d74a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""84a2922d-2776-4aa7-92b0-db235678fcde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""43e2faef-e223-4fcd-ab98-7b829c875bac"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""382923f3-b4f2-439a-8444-bb2e4d6ebb0c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""37d0e67e-a874-4f5a-b3f5-2e6ee261196b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""78232269-6955-4f56-a7f6-96b76e6561b7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""53a95117-1b9a-49cc-8a0c-530fb80299cf"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f2d20898-55bc-442b-ae4e-5261b45c1ffd"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02820234-de1a-4cf5-84ad-56073f787036"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f59cff7-b3ce-4542-b69f-317bd7224b65"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Objectives"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3c2a366-0029-4eb7-b178-5891bbe6940a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45a22677-f494-46fe-a4b9-2af1c132958b"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Piano"",
            ""id"": ""42b5a007-e4e0-45b0-8080-7621adf5e587"",
            ""actions"": [
                {
                    ""name"": ""C3"",
                    ""type"": ""Button"",
                    ""id"": ""1198fca8-9835-4b82-9ded-837ba925dddf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CS3"",
                    ""type"": ""Button"",
                    ""id"": ""e80bda9b-e2a3-4a84-b2eb-a8fb4624e8b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D3"",
                    ""type"": ""Button"",
                    ""id"": ""c0ad6f86-4e8f-4ca6-8c58-f8dee61e7f72"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DS3"",
                    ""type"": ""Button"",
                    ""id"": ""eda95aec-c3dc-425a-9d8f-2e6f99d49349"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E3"",
                    ""type"": ""Button"",
                    ""id"": ""ccb9c7b1-0db2-49b0-8e72-6ef0f80e7e30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F3"",
                    ""type"": ""Button"",
                    ""id"": ""749234f9-436d-409b-b0a4-0a67843fcfe5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FS3"",
                    ""type"": ""Button"",
                    ""id"": ""a4118a82-20ff-4f55-b540-b55f0c87fa6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""G3"",
                    ""type"": ""Button"",
                    ""id"": ""3aedfd43-7b47-4a60-8c35-1d45f1071f3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GS3"",
                    ""type"": ""Button"",
                    ""id"": ""9518fe35-d023-428f-90e4-f8b836037aeb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A3"",
                    ""type"": ""Button"",
                    ""id"": ""458477d7-d2e7-482d-9796-2061e11e4828"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AS3"",
                    ""type"": ""Button"",
                    ""id"": ""1602094e-9078-4b8e-b65e-49e448a25cc6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B3"",
                    ""type"": ""Button"",
                    ""id"": ""2fa9ea58-6fac-4ed4-a88a-aadc65ad0cff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""C4"",
                    ""type"": ""Button"",
                    ""id"": ""39ad355f-bba4-4e08-aa7d-e946d81b920c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CS4"",
                    ""type"": ""Button"",
                    ""id"": ""5c34fa2b-540e-4565-9ef7-725d6c933fb0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D4"",
                    ""type"": ""Button"",
                    ""id"": ""6aab6189-7405-483f-b795-f38730a42d92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DS4"",
                    ""type"": ""Button"",
                    ""id"": ""2015b4a5-3d83-4180-b299-7184bd87c46e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E4"",
                    ""type"": ""Button"",
                    ""id"": ""ac2280bb-d5ad-4e63-a393-fd168c02e664"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F4"",
                    ""type"": ""Button"",
                    ""id"": ""5e475ab4-ade1-4068-9cbc-270e23191fe1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0662a05c-db10-49a1-b89a-ab89dfcd5344"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c1777c4-d378-47c6-838b-de836f575c4a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5599c1f7-f6c4-4d12-8048-718a0d2edee2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b49319f7-d412-4762-84dd-a5fa67a93a2f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6cbeb5e-935b-4b86-b519-b133ba169ce1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3311dbe0-ee6e-49e6-995e-e852a9ce989d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1839890-158e-47f6-ba48-8741a2c16ccc"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d26437b-ee56-4fb3-b411-075fa214d49b"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""779069f6-a526-410d-bbcc-89e965f5657d"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c9e4f78-668b-4126-9ace-8bd891f22cc3"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe21e70b-250d-4b17-91c1-f241a38f0ff9"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88bcb752-5c31-4821-945b-38cee8f5c7b9"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cda9d61-5b79-493a-bdac-a7ba98d23d01"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""251abc38-d672-47e8-b97c-e7f802095a5f"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CS4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d96d0652-2be9-486e-97f3-88ac39659707"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34712cb7-1382-43a8-962a-3b486671c290"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DS4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a58aecba-1cd5-4c8e-ad53-06cbcf7e3d68"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4f49bc5-60fe-4ff6-bb5c-b8c13b067cd2"",
                    ""path"": ""<Keyboard>/quote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_MouseX = m_Player.FindAction("MouseX", throwIfNotFound: true);
        m_Player_MouseY = m_Player.FindAction("MouseY", throwIfNotFound: true);
        m_Player_Objectives = m_Player.FindAction("Objectives", throwIfNotFound: true);
        // Piano
        m_Piano = asset.FindActionMap("Piano", throwIfNotFound: true);
        m_Piano_C3 = m_Piano.FindAction("C3", throwIfNotFound: true);
        m_Piano_CS3 = m_Piano.FindAction("CS3", throwIfNotFound: true);
        m_Piano_D3 = m_Piano.FindAction("D3", throwIfNotFound: true);
        m_Piano_DS3 = m_Piano.FindAction("DS3", throwIfNotFound: true);
        m_Piano_E3 = m_Piano.FindAction("E3", throwIfNotFound: true);
        m_Piano_F3 = m_Piano.FindAction("F3", throwIfNotFound: true);
        m_Piano_FS3 = m_Piano.FindAction("FS3", throwIfNotFound: true);
        m_Piano_G3 = m_Piano.FindAction("G3", throwIfNotFound: true);
        m_Piano_GS3 = m_Piano.FindAction("GS3", throwIfNotFound: true);
        m_Piano_A3 = m_Piano.FindAction("A3", throwIfNotFound: true);
        m_Piano_AS3 = m_Piano.FindAction("AS3", throwIfNotFound: true);
        m_Piano_B3 = m_Piano.FindAction("B3", throwIfNotFound: true);
        m_Piano_C4 = m_Piano.FindAction("C4", throwIfNotFound: true);
        m_Piano_CS4 = m_Piano.FindAction("CS4", throwIfNotFound: true);
        m_Piano_D4 = m_Piano.FindAction("D4", throwIfNotFound: true);
        m_Piano_DS4 = m_Piano.FindAction("DS4", throwIfNotFound: true);
        m_Piano_E4 = m_Piano.FindAction("E4", throwIfNotFound: true);
        m_Piano_F4 = m_Piano.FindAction("F4", throwIfNotFound: true);
        m_Player_PickUp = m_Player.FindAction("PickUp", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_MouseX;
    private readonly InputAction m_Player_MouseY;
    private readonly InputAction m_Player_Objectives;
    private readonly InputAction m_Player_PickUp;
    private readonly InputAction m_Player_Crouch;
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @MouseX => m_Wrapper.m_Player_MouseX;
        public InputAction @MouseY => m_Wrapper.m_Player_MouseY;
        public InputAction @Objectives => m_Wrapper.m_Player_Objectives;
        public InputAction @PickUp => m_Wrapper.m_Player_PickUp;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @MouseX.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseX;
                @MouseX.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseX;
                @MouseX.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseX;
                @MouseY.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseY;
                @MouseY.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseY;
                @MouseY.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseY;
                @Objectives.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnObjectives;
                @Objectives.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnObjectives;
                @Objectives.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnObjectives;
                @PickUp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickUp;
                @PickUp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickUp;
                @PickUp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPickUp;
                @Crouch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @MouseX.started += instance.OnMouseX;
                @MouseX.performed += instance.OnMouseX;
                @MouseX.canceled += instance.OnMouseX;
                @MouseY.started += instance.OnMouseY;
                @MouseY.performed += instance.OnMouseY;
                @MouseY.canceled += instance.OnMouseY;
                @Objectives.started += instance.OnObjectives;
                @Objectives.performed += instance.OnObjectives;
                @Objectives.canceled += instance.OnObjectives;
                @PickUp.started += instance.OnPickUp;
                @PickUp.performed += instance.OnPickUp;
                @PickUp.canceled += instance.OnPickUp;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Piano
    private readonly InputActionMap m_Piano;
    private IPianoActions m_PianoActionsCallbackInterface;
    private readonly InputAction m_Piano_C3;
    private readonly InputAction m_Piano_CS3;
    private readonly InputAction m_Piano_D3;
    private readonly InputAction m_Piano_DS3;
    private readonly InputAction m_Piano_E3;
    private readonly InputAction m_Piano_F3;
    private readonly InputAction m_Piano_FS3;
    private readonly InputAction m_Piano_G3;
    private readonly InputAction m_Piano_GS3;
    private readonly InputAction m_Piano_A3;
    private readonly InputAction m_Piano_AS3;
    private readonly InputAction m_Piano_B3;
    private readonly InputAction m_Piano_C4;
    private readonly InputAction m_Piano_CS4;
    private readonly InputAction m_Piano_D4;
    private readonly InputAction m_Piano_DS4;
    private readonly InputAction m_Piano_E4;
    private readonly InputAction m_Piano_F4;
    public struct PianoActions
    {
        private @InputActions m_Wrapper;
        public PianoActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @C3 => m_Wrapper.m_Piano_C3;
        public InputAction @CS3 => m_Wrapper.m_Piano_CS3;
        public InputAction @D3 => m_Wrapper.m_Piano_D3;
        public InputAction @DS3 => m_Wrapper.m_Piano_DS3;
        public InputAction @E3 => m_Wrapper.m_Piano_E3;
        public InputAction @F3 => m_Wrapper.m_Piano_F3;
        public InputAction @FS3 => m_Wrapper.m_Piano_FS3;
        public InputAction @G3 => m_Wrapper.m_Piano_G3;
        public InputAction @GS3 => m_Wrapper.m_Piano_GS3;
        public InputAction @A3 => m_Wrapper.m_Piano_A3;
        public InputAction @AS3 => m_Wrapper.m_Piano_AS3;
        public InputAction @B3 => m_Wrapper.m_Piano_B3;
        public InputAction @C4 => m_Wrapper.m_Piano_C4;
        public InputAction @CS4 => m_Wrapper.m_Piano_CS4;
        public InputAction @D4 => m_Wrapper.m_Piano_D4;
        public InputAction @DS4 => m_Wrapper.m_Piano_DS4;
        public InputAction @E4 => m_Wrapper.m_Piano_E4;
        public InputAction @F4 => m_Wrapper.m_Piano_F4;
        public InputActionMap Get() { return m_Wrapper.m_Piano; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PianoActions set) { return set.Get(); }
        public void SetCallbacks(IPianoActions instance)
        {
            if (m_Wrapper.m_PianoActionsCallbackInterface != null)
            {
                @C3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnC3;
                @C3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnC3;
                @C3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnC3;
                @CS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS3;
                @CS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS3;
                @CS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS3;
                @D3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnD3;
                @D3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnD3;
                @D3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnD3;
                @DS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS3;
                @DS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS3;
                @DS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS3;
                @E3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnE3;
                @E3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnE3;
                @E3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnE3;
                @F3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnF3;
                @F3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnF3;
                @F3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnF3;
                @FS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS3;
                @FS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS3;
                @FS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnFS3;
                @G3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnG3;
                @G3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnG3;
                @G3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnG3;
                @GS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS3;
                @GS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS3;
                @GS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnGS3;
                @A3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnA3;
                @A3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnA3;
                @A3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnA3;
                @AS3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS3;
                @AS3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS3;
                @AS3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnAS3;
                @B3.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnB3;
                @B3.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnB3;
                @B3.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnB3;
                @C4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnC4;
                @C4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnC4;
                @C4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnC4;
                @CS4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS4;
                @CS4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS4;
                @CS4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnCS4;
                @D4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnD4;
                @D4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnD4;
                @D4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnD4;
                @DS4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS4;
                @DS4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS4;
                @DS4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnDS4;
                @E4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnE4;
                @E4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnE4;
                @E4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnE4;
                @F4.started -= m_Wrapper.m_PianoActionsCallbackInterface.OnF4;
                @F4.performed -= m_Wrapper.m_PianoActionsCallbackInterface.OnF4;
                @F4.canceled -= m_Wrapper.m_PianoActionsCallbackInterface.OnF4;
            }
            m_Wrapper.m_PianoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @C3.started += instance.OnC3;
                @C3.performed += instance.OnC3;
                @C3.canceled += instance.OnC3;
                @CS3.started += instance.OnCS3;
                @CS3.performed += instance.OnCS3;
                @CS3.canceled += instance.OnCS3;
                @D3.started += instance.OnD3;
                @D3.performed += instance.OnD3;
                @D3.canceled += instance.OnD3;
                @DS3.started += instance.OnDS3;
                @DS3.performed += instance.OnDS3;
                @DS3.canceled += instance.OnDS3;
                @E3.started += instance.OnE3;
                @E3.performed += instance.OnE3;
                @E3.canceled += instance.OnE3;
                @F3.started += instance.OnF3;
                @F3.performed += instance.OnF3;
                @F3.canceled += instance.OnF3;
                @FS3.started += instance.OnFS3;
                @FS3.performed += instance.OnFS3;
                @FS3.canceled += instance.OnFS3;
                @G3.started += instance.OnG3;
                @G3.performed += instance.OnG3;
                @G3.canceled += instance.OnG3;
                @GS3.started += instance.OnGS3;
                @GS3.performed += instance.OnGS3;
                @GS3.canceled += instance.OnGS3;
                @A3.started += instance.OnA3;
                @A3.performed += instance.OnA3;
                @A3.canceled += instance.OnA3;
                @AS3.started += instance.OnAS3;
                @AS3.performed += instance.OnAS3;
                @AS3.canceled += instance.OnAS3;
                @B3.started += instance.OnB3;
                @B3.performed += instance.OnB3;
                @B3.canceled += instance.OnB3;
                @C4.started += instance.OnC4;
                @C4.performed += instance.OnC4;
                @C4.canceled += instance.OnC4;
                @CS4.started += instance.OnCS4;
                @CS4.performed += instance.OnCS4;
                @CS4.canceled += instance.OnCS4;
                @D4.started += instance.OnD4;
                @D4.performed += instance.OnD4;
                @D4.canceled += instance.OnD4;
                @DS4.started += instance.OnDS4;
                @DS4.performed += instance.OnDS4;
                @DS4.canceled += instance.OnDS4;
                @E4.started += instance.OnE4;
                @E4.performed += instance.OnE4;
                @E4.canceled += instance.OnE4;
                @F4.started += instance.OnF4;
                @F4.performed += instance.OnF4;
                @F4.canceled += instance.OnF4;
            }
        }
    }
    public PianoActions @Piano => new PianoActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnObjectives(InputAction.CallbackContext context);
        void OnPickUp(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
    }
    public interface IPianoActions
    {
        void OnC3(InputAction.CallbackContext context);
        void OnCS3(InputAction.CallbackContext context);
        void OnD3(InputAction.CallbackContext context);
        void OnDS3(InputAction.CallbackContext context);
        void OnE3(InputAction.CallbackContext context);
        void OnF3(InputAction.CallbackContext context);
        void OnFS3(InputAction.CallbackContext context);
        void OnG3(InputAction.CallbackContext context);
        void OnGS3(InputAction.CallbackContext context);
        void OnA3(InputAction.CallbackContext context);
        void OnAS3(InputAction.CallbackContext context);
        void OnB3(InputAction.CallbackContext context);
        void OnC4(InputAction.CallbackContext context);
        void OnCS4(InputAction.CallbackContext context);
        void OnD4(InputAction.CallbackContext context);
        void OnDS4(InputAction.CallbackContext context);
        void OnE4(InputAction.CallbackContext context);
        void OnF4(InputAction.CallbackContext context);
    }
}
