//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/PianoActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PianoActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PianoActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PianoActions"",
    ""maps"": [
        {
            ""name"": ""Play"",
            ""id"": ""2271822a-a583-402c-b60c-41fd7532399e"",
            ""actions"": [
                {
                    ""name"": ""C3"",
                    ""type"": ""Button"",
                    ""id"": ""dc33a7bd-846f-4e2a-9a8d-ec60edc2e161"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CS3"",
                    ""type"": ""Button"",
                    ""id"": ""47b86d22-2d86-4e1a-9e41-a3fb2d8c3306"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D3"",
                    ""type"": ""Button"",
                    ""id"": ""32e3c5fb-053d-4ce8-ab8c-a682a412ffc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DS3"",
                    ""type"": ""Button"",
                    ""id"": ""683f58cf-4fd6-4209-95c6-75f1ea13edb0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E3"",
                    ""type"": ""Button"",
                    ""id"": ""114d3a72-fb36-45be-8b80-487dff36b385"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F3"",
                    ""type"": ""Button"",
                    ""id"": ""8e3b2d55-77d2-40ea-8d79-0210c17dfd9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FS3"",
                    ""type"": ""Button"",
                    ""id"": ""47ecbabf-a366-4980-9e16-2676678958d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""G3"",
                    ""type"": ""Button"",
                    ""id"": ""f6a8e799-9749-40fc-8ba5-e3aa3e6707ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GS3"",
                    ""type"": ""Button"",
                    ""id"": ""ebe5e85c-e382-4645-9977-d4a652c46187"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A3"",
                    ""type"": ""Button"",
                    ""id"": ""5677c9bb-b882-4a25-ab8d-2ec3958232fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AS3"",
                    ""type"": ""Button"",
                    ""id"": ""fd4b8d5e-0ac7-4ba8-90c8-69819e7c76f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B3"",
                    ""type"": ""Button"",
                    ""id"": ""7e071482-7eae-45c7-b09c-d7beeacf54b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""C4"",
                    ""type"": ""Button"",
                    ""id"": ""e47868bc-b368-4a24-8a40-3db155f3e602"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CS4"",
                    ""type"": ""Button"",
                    ""id"": ""fa27b1e8-0139-4be1-badf-cdf1aebb948c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D4"",
                    ""type"": ""Button"",
                    ""id"": ""9a1c1486-ad28-4049-b640-3926464bcc5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DS4"",
                    ""type"": ""Button"",
                    ""id"": ""9454c31b-65c7-469c-9557-982dd84175dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E4"",
                    ""type"": ""Button"",
                    ""id"": ""a4a30f53-0e02-432d-ab92-055712258ac5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F4"",
                    ""type"": ""Button"",
                    ""id"": ""8f4a5588-0489-4216-898a-4e05d8af3bc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4da4a712-2b07-4d20-97a5-f4b9e94c1e71"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7787ac2-d7d9-42c5-a526-393304c2d001"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95040c04-9e42-4931-8774-dd52d49893a5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4806290b-a908-4ea5-a62d-9c5532ffa04d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81779bbb-d041-4c0f-ae85-0dc2e1ed4083"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29c37587-dfac-4cd4-853f-63ed8c90558c"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b977d4b7-1357-40b9-8553-65cae49ef5ef"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26953608-f656-443c-9229-98958e651281"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c027a429-ebeb-4e7a-9b7f-4759e77e912f"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e1b10c0-3746-43fd-9eab-4be40bfd6e4e"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""186de1f2-9d0e-4772-804a-324777bd6fd4"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AS3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a871929-d5c7-41f4-9e90-61ceb0cc499c"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b40fe651-62c2-4f06-9c35-e91491cd4b75"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7eed4bb4-66f5-4b32-bb8b-c70dc18c823e"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CS4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec8067f2-cb54-40cb-b6bb-8e178ec62fb6"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b49dbf10-1d89-4dc1-bc46-47a3ec84a01f"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DS4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3833c9b4-1ded-4b29-9a38-1d4babc2a1b8"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7b79ec3-370e-446c-9d5d-c4453837f544"",
                    ""path"": ""<Keyboard>/quote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Play
        m_Play = asset.FindActionMap("Play", throwIfNotFound: true);
        m_Play_C3 = m_Play.FindAction("C3", throwIfNotFound: true);
        m_Play_CS3 = m_Play.FindAction("CS3", throwIfNotFound: true);
        m_Play_D3 = m_Play.FindAction("D3", throwIfNotFound: true);
        m_Play_DS3 = m_Play.FindAction("DS3", throwIfNotFound: true);
        m_Play_E3 = m_Play.FindAction("E3", throwIfNotFound: true);
        m_Play_F3 = m_Play.FindAction("F3", throwIfNotFound: true);
        m_Play_FS3 = m_Play.FindAction("FS3", throwIfNotFound: true);
        m_Play_G3 = m_Play.FindAction("G3", throwIfNotFound: true);
        m_Play_GS3 = m_Play.FindAction("GS3", throwIfNotFound: true);
        m_Play_A3 = m_Play.FindAction("A3", throwIfNotFound: true);
        m_Play_AS3 = m_Play.FindAction("AS3", throwIfNotFound: true);
        m_Play_B3 = m_Play.FindAction("B3", throwIfNotFound: true);
        m_Play_C4 = m_Play.FindAction("C4", throwIfNotFound: true);
        m_Play_CS4 = m_Play.FindAction("CS4", throwIfNotFound: true);
        m_Play_D4 = m_Play.FindAction("D4", throwIfNotFound: true);
        m_Play_DS4 = m_Play.FindAction("DS4", throwIfNotFound: true);
        m_Play_E4 = m_Play.FindAction("E4", throwIfNotFound: true);
        m_Play_F4 = m_Play.FindAction("F4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Play
    private readonly InputActionMap m_Play;
    private IPlayActions m_PlayActionsCallbackInterface;
    private readonly InputAction m_Play_C3;
    private readonly InputAction m_Play_CS3;
    private readonly InputAction m_Play_D3;
    private readonly InputAction m_Play_DS3;
    private readonly InputAction m_Play_E3;
    private readonly InputAction m_Play_F3;
    private readonly InputAction m_Play_FS3;
    private readonly InputAction m_Play_G3;
    private readonly InputAction m_Play_GS3;
    private readonly InputAction m_Play_A3;
    private readonly InputAction m_Play_AS3;
    private readonly InputAction m_Play_B3;
    private readonly InputAction m_Play_C4;
    private readonly InputAction m_Play_CS4;
    private readonly InputAction m_Play_D4;
    private readonly InputAction m_Play_DS4;
    private readonly InputAction m_Play_E4;
    private readonly InputAction m_Play_F4;
    public struct PlayActions
    {
        private @PianoActions m_Wrapper;
        public PlayActions(@PianoActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @C3 => m_Wrapper.m_Play_C3;
        public InputAction @CS3 => m_Wrapper.m_Play_CS3;
        public InputAction @D3 => m_Wrapper.m_Play_D3;
        public InputAction @DS3 => m_Wrapper.m_Play_DS3;
        public InputAction @E3 => m_Wrapper.m_Play_E3;
        public InputAction @F3 => m_Wrapper.m_Play_F3;
        public InputAction @FS3 => m_Wrapper.m_Play_FS3;
        public InputAction @G3 => m_Wrapper.m_Play_G3;
        public InputAction @GS3 => m_Wrapper.m_Play_GS3;
        public InputAction @A3 => m_Wrapper.m_Play_A3;
        public InputAction @AS3 => m_Wrapper.m_Play_AS3;
        public InputAction @B3 => m_Wrapper.m_Play_B3;
        public InputAction @C4 => m_Wrapper.m_Play_C4;
        public InputAction @CS4 => m_Wrapper.m_Play_CS4;
        public InputAction @D4 => m_Wrapper.m_Play_D4;
        public InputAction @DS4 => m_Wrapper.m_Play_DS4;
        public InputAction @E4 => m_Wrapper.m_Play_E4;
        public InputAction @F4 => m_Wrapper.m_Play_F4;
        public InputActionMap Get() { return m_Wrapper.m_Play; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayActions set) { return set.Get(); }
        public void SetCallbacks(IPlayActions instance)
        {
            if (m_Wrapper.m_PlayActionsCallbackInterface != null)
            {
                @C3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnC3;
                @C3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnC3;
                @C3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnC3;
                @CS3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnCS3;
                @CS3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnCS3;
                @CS3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnCS3;
                @D3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnD3;
                @D3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnD3;
                @D3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnD3;
                @DS3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnDS3;
                @DS3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnDS3;
                @DS3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnDS3;
                @E3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnE3;
                @E3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnE3;
                @E3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnE3;
                @F3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnF3;
                @F3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnF3;
                @F3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnF3;
                @FS3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnFS3;
                @FS3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnFS3;
                @FS3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnFS3;
                @G3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnG3;
                @G3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnG3;
                @G3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnG3;
                @GS3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnGS3;
                @GS3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnGS3;
                @GS3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnGS3;
                @A3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnA3;
                @A3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnA3;
                @A3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnA3;
                @AS3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnAS3;
                @AS3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnAS3;
                @AS3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnAS3;
                @B3.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnB3;
                @B3.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnB3;
                @B3.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnB3;
                @C4.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnC4;
                @C4.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnC4;
                @C4.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnC4;
                @CS4.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnCS4;
                @CS4.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnCS4;
                @CS4.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnCS4;
                @D4.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnD4;
                @D4.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnD4;
                @D4.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnD4;
                @DS4.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnDS4;
                @DS4.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnDS4;
                @DS4.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnDS4;
                @E4.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnE4;
                @E4.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnE4;
                @E4.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnE4;
                @F4.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnF4;
                @F4.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnF4;
                @F4.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnF4;
            }
            m_Wrapper.m_PlayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @C3.started += instance.OnC3;
                @C3.performed += instance.OnC3;
                @C3.canceled += instance.OnC3;
                @CS3.started += instance.OnCS3;
                @CS3.performed += instance.OnCS3;
                @CS3.canceled += instance.OnCS3;
                @D3.started += instance.OnD3;
                @D3.performed += instance.OnD3;
                @D3.canceled += instance.OnD3;
                @DS3.started += instance.OnDS3;
                @DS3.performed += instance.OnDS3;
                @DS3.canceled += instance.OnDS3;
                @E3.started += instance.OnE3;
                @E3.performed += instance.OnE3;
                @E3.canceled += instance.OnE3;
                @F3.started += instance.OnF3;
                @F3.performed += instance.OnF3;
                @F3.canceled += instance.OnF3;
                @FS3.started += instance.OnFS3;
                @FS3.performed += instance.OnFS3;
                @FS3.canceled += instance.OnFS3;
                @G3.started += instance.OnG3;
                @G3.performed += instance.OnG3;
                @G3.canceled += instance.OnG3;
                @GS3.started += instance.OnGS3;
                @GS3.performed += instance.OnGS3;
                @GS3.canceled += instance.OnGS3;
                @A3.started += instance.OnA3;
                @A3.performed += instance.OnA3;
                @A3.canceled += instance.OnA3;
                @AS3.started += instance.OnAS3;
                @AS3.performed += instance.OnAS3;
                @AS3.canceled += instance.OnAS3;
                @B3.started += instance.OnB3;
                @B3.performed += instance.OnB3;
                @B3.canceled += instance.OnB3;
                @C4.started += instance.OnC4;
                @C4.performed += instance.OnC4;
                @C4.canceled += instance.OnC4;
                @CS4.started += instance.OnCS4;
                @CS4.performed += instance.OnCS4;
                @CS4.canceled += instance.OnCS4;
                @D4.started += instance.OnD4;
                @D4.performed += instance.OnD4;
                @D4.canceled += instance.OnD4;
                @DS4.started += instance.OnDS4;
                @DS4.performed += instance.OnDS4;
                @DS4.canceled += instance.OnDS4;
                @E4.started += instance.OnE4;
                @E4.performed += instance.OnE4;
                @E4.canceled += instance.OnE4;
                @F4.started += instance.OnF4;
                @F4.performed += instance.OnF4;
                @F4.canceled += instance.OnF4;
            }
        }
    }
    public PlayActions @Play => new PlayActions(this);
    public interface IPlayActions
    {
        void OnC3(InputAction.CallbackContext context);
        void OnCS3(InputAction.CallbackContext context);
        void OnD3(InputAction.CallbackContext context);
        void OnDS3(InputAction.CallbackContext context);
        void OnE3(InputAction.CallbackContext context);
        void OnF3(InputAction.CallbackContext context);
        void OnFS3(InputAction.CallbackContext context);
        void OnG3(InputAction.CallbackContext context);
        void OnGS3(InputAction.CallbackContext context);
        void OnA3(InputAction.CallbackContext context);
        void OnAS3(InputAction.CallbackContext context);
        void OnB3(InputAction.CallbackContext context);
        void OnC4(InputAction.CallbackContext context);
        void OnCS4(InputAction.CallbackContext context);
        void OnD4(InputAction.CallbackContext context);
        void OnDS4(InputAction.CallbackContext context);
        void OnE4(InputAction.CallbackContext context);
        void OnF4(InputAction.CallbackContext context);
    }
}
